### ISSUE TITLE
Packagist Todo

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/laravel-notification-channels.github.io#25]
I don't have access to the packagist account. This issue will track what needs to be done to get everything up to date.

We can't update most of the channels to support new laravel versions 😞 

Fix webhooks so new versions can be released:
- [x] https://github.com/laravel-notification-channels/bearychat/issues/12
- [x] https://github.com/laravel-notification-channels/webhook/issues/29
- [x] https://github.com/laravel-notification-channels/apn/issues/62
- [x] https://github.com/laravel-notification-channels/webpush/issues/100
- [x] https://github.com/laravel-notification-channels/messagebird/issues/23
- [x] https://github.com/laravel-notification-channels/onesignal/issues/101
- [x] https://github.com/laravel-notification-channels/pushover/issues/36
- [x] https://github.com/laravel-notification-channels/twilio/issues/66
- [x] https://github.com/laravel-notification-channels/cmsms/issues/11
- [x] https://github.com/laravel-notification-channels/pusher-push-notifications/issues/32
- [x] https://github.com/laravel-notification-channels/plivo/issues/25
- [x] https://github.com/laravel-notification-channels/discord/issues/29

Publish new channels:
- [x] https://github.com/laravel-notification-channels/pushwoosh
- [x] https://github.com/laravel-notification-channels/sms-broadcast
- [x] https://github.com/laravel-notification-channels/46elks/issues/1 (waiting on PR merge)
- [ ] https://github.com/laravel-notification-channels/fcm/issues/1 (waiting on PR merge)

Deprecate (mark as abandoned) dead packages:
- [x] https://github.com/laravel-notification-channels/maillift
- [x] https://github.com/laravel-notification-channels/hipchat
- [ ] https://github.com/laravel-notification-channels/gammu
- [x] https://github.com/laravel-notification-channels/ionic-push-notifications

cc @themsaid @freekmurze

**Comment by atymic** [comment]
@freekmurze @mpociot @themsaid 

Sorry to bug you guys, but is anyone able to get a message to Mohamed?
We're blocked on a lot of channels 😞

**Comment by Diddyy** [comment]
Would also like to chime in, also waiting on the new release. Particularly for /discord 
@themsaid @freekmurze @mpociot

**Comment by vincentdh** [comment]
Is this project dead? @atymic is working hard on the repos but he don't have access to packagist ... Help please?  News?

@themsaid @freekmurze @mpociot

**Comment by atymic** [comment]
I haven't been able able to get in contact with him yet. It seems he's around on github commiting and on twitter :(

I've tweeted at him, emailed him and tagged him on here, so I'm not sure how else to get in contact with him.

**Comment by themsaid** [comment]
Hey guys,

I'm sorry but I don't have enough time nowadays to manage these repos. I can move the repo ownership to someone who's willing to manage these. Please let me know if you're willing.

**Comment by atymic** [comment]
Hey @themsaid 🙌 

I've been maintaining the github repos, I just don't have packagist access.

Could you give me access to the packagist account:
https://packagist.org/users/laravel-notification-channels/

If you are able to add me as a maintainer instead, my packagist account is:
https://packagist.org/users/atymic/

You can contact me via email at: atymicq@gmail.com, or on twitter at: https://twitter.com/atymic

Thanks 😄

**Comment by atymic** [comment]
Huge shout out to Mohamed 🙌 

I've fixed the webhooks for the repos with issues and will be working on new releases/deperacations soon. 

Thanks everyone for your patience 😃
